use_frameworks!

platform :ios, '9.0'

target 'LSJHImageBrowser_Example' do
  pod 'LSJHImageBrowser', :path => '../'

  target 'LSJHImageBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
